Orbital/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from accounts import views as accounts_views
from survey import views as survey_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

# urlpatterns = [
#     path('accounts/', include('accounts.urls')),
#     path('admin/', admin.site.urls)
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('survey.urls')),
    url(r'^$',accounts_views.index,name='index'),
    url(r'^special/',accounts_views.special,name='special'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^accounts/profile/',accounts_views.profile_view, name='profile'),
    url(r'^logout/$', accounts_views.user_logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'accounts'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('login/',views.login_view,name='login'),
#     path('signup/',views.signup_view, name='signup')
# ]

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login, name='user_login'),
    url(r'^profile/$', views.profile_view, name='profile')
    
]

survey/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import url
from survey import views as survey_views
from accounts import views as accounts_views
from .views import SurveyListView, SurveyDetailView, SurveyCreateView, SurveyUpdateView, SurveyDeleteView


app_name = 'survey'

urlpatterns=[
    path('dashboard/', survey_views.dashboard_view, name='dashboard'),
    path('survey/', survey_views.survey_view, name='survey'),
    path('uploadsurvey/', SurveyCreateView.as_view(), name='uploadsurvey'),
    #path('tracksurvey/', SurveyListView.as_view() , name='tracksurvey'),
    path('tracksurvey/', survey_views.tracksurvey_view , name='tracksurvey'),
    path('tracksurvey/survey/<int:pk>/', SurveyDetailView.as_view() , name='tracksurvey-detail'),
    path('rewards/', survey_views.rewards_view, name='rewards'),
    path('tracksurvey/survey/<int:pk>/update/', SurveyUpdateView.as_view(), name='updatesurvey'),
    path('tracksurvey/survey/<int:pk>/delete/', SurveyDeleteView.as_view(), name='deletesurvey'),
    path('completedsurveys/', survey_views.completedsurveys_view , name='completedsurveys'),
    path('dashboard/<int:pk>/', survey_views.completedsurveys_update , name='completedsurveys_update'),
    path('rewards/', survey_views.rewards_view, name='rewards'),
    path('shoprewards/', survey_views.shoprewards_view, name='shoprewards'),
    path('rewards/<int:pk>', survey_views.redeem_update, name='redeem_update'),
    path('redeemedrewards/', survey_views.redeemedrewards_view , name='redeemedrewards'),
    path('redeemedrewards/<int:pk>', survey_views.used_update, name='used_update'),
    path('usedrewards/', survey_views.usedrewards_view, name='usedrewards'),
    path('report/', survey_views.report_view, name='report'),
    path('privacy/', survey_views.privacy_view, name='privacy')

]

survey/forms.py
from django.forms import ModelForm
from django import forms
from .models import UploadSurvey,Report
import datetime

class UploadSurveyForm(forms.ModelForm):

    class Meta():
        model = UploadSurvey
        fields = ('surveytitle','surveylink','surveydescription','surveycategory','gender_filter','singaporean_filter','faculty_filter','year_filter','residential_filter')
        widgets={
            'surveytitle': forms.TextInput(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'}),
            'surveylink': forms.TextInput(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'}),
            'surveydescription':forms.Textarea(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'}),
            'surveycategory':forms.Select(attrs={'id':'login-input-user', 'class':'login__input','style': 'width:430px'}),
            'gender_filter': forms.CheckboxSelectMultiple(attrs={'checked' : 'checked'}),
            'singaporean_filter': forms.CheckboxSelectMultiple(attrs={'checked' : 'checked'}),
            'faculty_filter': forms.CheckboxSelectMultiple(attrs={'checked' : 'checked'}),
            'year_filter': forms.CheckboxSelectMultiple(attrs={'checked' : 'checked'}),
            'residential_filter': forms.CheckboxSelectMultiple(attrs={'checked' : 'checked'})

            
        }

class ReportForm(forms.ModelForm):
    class Meta():
        model = Report
        fields = ('user','subject','details')
        widgets={
            'user': forms.Select(attrs={'id':'login-input-user','class':'login__input'}),
            'subject':forms.TextInput(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input','style':'width:360px'}),
            'details':forms.Textarea(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'})
        }

survey/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import UploadSurveyForm,ReportForm
from .models import UploadSurvey,CompletedSurveys, TotalPoints, Reward, RedeemedRewards, UsedRewards,Report
from accounts.models import UserProfileInfo
from django.contrib import messages
from django.contrib.auth.models import User
from datetime import datetime
from django.views.generic import ListView, DetailView, CreateView,UpdateView, DeleteView
from django import forms
from .filters import SurveyFilter
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Avg, Sum
from django.db.models import F

@login_required
def dashboard_view(request):
    try:
        profile=request.user.userprofileinfo
    except:
        profile=UserProfileInfo.objects.create(user=request.user)
        messages.success(request,'Please update your profile')
        
    try:
        target_filter= UploadSurvey.objects.filter(
                gender_filter__gender_filter=profile.gender, 
                year_filter__year_filter=profile.year_in_school, 
                faculty_filter__faculty_filter=profile.faculty, 
                singaporean_filter__singaporean_filter=profile.singaporean,
                residential_filter__residential_filter=profile.currentresidentialtype
                
            ).exclude(user=request.user).exclude(id__in=CompletedSurveys.objects.get(user=request.user).completedsurveys.values_list('id',flat=True))
        
    except:
        target_filter= UploadSurvey.objects.filter(
                gender_filter__gender_filter=profile.gender, 
                year_filter__year_filter=profile.year_in_school, 
                faculty_filter__faculty_filter=profile.faculty, 
                singaporean_filter__singaporean_filter=profile.singaporean,
                residential_filter__residential_filter=profile.currentresidentialtype
            ).exclude(user=request.user)


    survey_filter= SurveyFilter(request.GET, queryset=target_filter)
    context={
        'displayedpoints': TotalPoints.objects.get_or_create(user=request.user),
        'dashboardfilter': survey_filter
    }
    return render(request, 'survey/dashboard.html',context)

@login_required
def survey_view(request):
    return render(request, 'survey/survey.html')



### VIEWS FOR UPLOADSURVEY
class SurveyCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model=UploadSurvey
    form_class = UploadSurveyForm
    success_message = "Your survey was created successfully"
    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)

class SurveyDeleteView(LoginRequiredMixin,UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model=UploadSurvey
    success_message = "Your survey was successfully deleted!"
    success_url='/tracksurvey/'

    def test_func(self):
        survey=self.get_object()
        if self.request.user == survey.user:
            return True
        return False

class SurveyUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model=UploadSurvey
    form_class=UploadSurveyForm
    success_message = "Your survey was successfully updated!"

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)

    def test_func(self):
        survey=self.get_object()
        if self.request.user == survey.user:
            return True
        return False


### VIEWS FOR TRACKSURVEY
@login_required
def tracksurvey_view(request):
    context = {
        'displayedsurveys': UploadSurvey.objects.filter(user=request.user)
    }
    return render(request, 'survey/tracksurvey.html', context)

class SurveyListView(LoginRequiredMixin,ListView):
    model=UploadSurvey
    template_name = 'survey/tracksurvey.html'
    context_object_name= 'allsurveys'
    ordering=['-uploadDate']

class SurveyDetailView(DetailView):
    model=UploadSurvey


### VIEWS FOR COMPLETEDSURVEYS
def completedsurveys_view(request):
    try:
        context = {
            'allcompletedsurveys': CompletedSurveys.objects.get(user=request.user)
        }
    
    except:
        context={
            'allcompletedsurveys': None
        }
    return render(request, 'survey/completedsurveys.html', context)


### VIEWS FOR NEWLY COMPLETED SURVEY
def completedsurveys_update(request, pk):
    try:
        user_completedsurveys = CompletedSurveys.objects.get(user=request.user)
    except ObjectDoesNotExist:
        user_completedsurveys = CompletedSurveys.objects.create(user=request.user)
        user_completedsurveys.save()

    newsurvey = UploadSurvey.objects.get(pk=pk)
    user_completedsurveys.completedsurveys.add(newsurvey)

    try:
        user_totalpoints = TotalPoints.objects.get(user=request.user)
    except ObjectDoesNotExist:
        user_totalpoints = TotalPoints.objects.create(user=request.user)
        user_totalpoints = TotalPoints.objects.get(user=request.user)

    user_totalpoints.points = F('points') + 1
    user_totalpoints.save()

    messages.success(request, 'Survey {} completed successfully'.format(pk))
    return redirect('survey:dashboard')


### VIEWS FOR REWARDS
@login_required
def rewards_view(request):
    return render(request, 'survey/rewards.html')


@login_required
def shoprewards_view(request):
    context={
        'displayedpoints': TotalPoints.objects.get_or_create(user=request.user),
        'displayedrewards':Reward.objects.all()
    }
    return render(request, 'survey/shoprewards.html', context)


def redeem_update(request,pk):
    try:
        user_redeemedrewards = RedeemedRewards.objects.get(user=request.user)
    except ObjectDoesNotExist:
        user_redeemedrewards = RedeemedRewards.objects.create(user=request.user)
        user_redeemedrewards.save()

    newredeemedreward = Reward.objects.get(pk=pk)
    

    user_totalpoints = TotalPoints.objects.get(user=request.user)
    requiredpoints = newredeemedreward.requiredpoints

    if user_totalpoints.points < requiredpoints:
        messages.error(request, 'Insufficient points to redeem reward')
    else:
        user_totalpoints.points = F('points') - requiredpoints
        user_totalpoints.save()
        user_redeemedrewards.redeemedrewards.add(newredeemedreward)
        messages.success(request, 'Reward {} redeemed successfully'.format(pk))
        
    return redirect('survey:shoprewards')


### VIEWS FOR REDEEMEDREWARDS
def redeemedrewards_view(request):
    try:
        context = {
            'displayedpoints': TotalPoints.objects.get_or_create(user=request.user),
            'allredeemedrewards': RedeemedRewards.objects.get_or_create(user=request.user).redeemedrewards.all()
        }
    except:
        context={
            'displayedpoints': TotalPoints.objects.get_or_create(user=request.user),
            'allredeemedrewards': RedeemedRewards.objects.get(user=request.user).redeemedrewards.all()
        }
    

    return render(request, 'survey/redeemedrewards.html', context)

def used_update(request,pk):
    try:
        user_usedrewards = UsedRewards.objects.get(user=request.user)
        user_redeemedrewards=RedeemedRewards.objects.get(user=request.user)

    except ObjectDoesNotExist:
        user_usedrewards = UsedRewards.objects.create(user=request.user)
        user_redeemedrewards = RedeemedRewards.objects.get(user=request.user)
        user_usedrewards.save()

    newusedreward = Reward.objects.get(pk=pk)
    user_usedrewards.usedrewards.add(newusedreward)
    user_redeemedrewards.redeemedrewards.remove(newusedreward)

    return redirect('survey:redeemedrewards')


### VIEW FOR USEDREWARDS
def usedrewards_view(request):
    try:
        context = {
            'displayedpoints': TotalPoints.objects.get_or_create(user=request.user),
            'allusedrewards': UsedRewards.objects.get(user=request.user)
        }
    
    except:
        context={
            'displayedpoints': TotalPoints.objects.get_or_create(user=request.user),
            'allusedrewards':None
        }
    return render(request, 'survey/usedrewards.html', context)


### VIEW FOR REPORT
@login_required
def report_view(request):
    if request.method == 'POST':
        report_form = ReportForm(request.POST)
        if report_form.is_valid():
            rf=report_form.save(commit=False)
            rf.user=request.user
            rf.save()
            messages.success(request, 'Your report is successfully made!')
            return redirect('survey:dashboard')
    else:
        report_form = ReportForm(instance=request.user)
    return render(request, 'survey/report.html', {'form':report_form})

def privacy_view(request):
    return render(request,'survey/privacy.html')

survey/templates/survey/dashboard.html
{% extends "survey/base.html" %}
{% load static %}
{% block css %}
<!-- link to tracksurvey.css -->
<link rel="stylesheet" type="text/css" href="{% static 'survey/tracksurvey.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/profile.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'survey/dashboard.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'survey/rewards.css'%}">
{% endblock %}

{% block navbar %}
<div class="nav_box">
<header class="navbarheader">
<div class=nav>
  <ul class=navbarlist>
    <a href="{% url 'survey:dashboard' %}" role="button" class="active">Home</a>
    <a href="{% url 'accounts:profile' %}" role="button">Profile</a>
    <a href="{% url 'survey:survey' %}" role="button" >Survey</a>
    <a href="{% url 'survey:shoprewards' %}" role="button">Rewards</a>
    <a href="{% url 'survey:report' %}" role="button">Report</a>
    <a href="{% url 'logout' %}" id="logout">Logout</a>
  </ul>
</div>
</header>
</div>
{% endblock %}


{% block body_block %}
{% load widget_tweaks %}

<div class="stars"></div>
<div class="twinkling"></div>
<div class="clouds"></div>


<!-- <div class="reward">
  <div class="dashpoints">
    Total Available Points
  </div>

  <div class="box submit-button">
    <a href="#" id="update-button">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        {% for user in displayedpoints %}
     {{user.points}}
  {% endfor %}
    </a>
  </div>

<div> -->
  <div id="about-us">
    <h1> Welcome to NUadvertS! </h1>
    <h3> This is a one-stop and comprehensive platform where survey conductors can conveniently source
      <br> for survey respondents
    and many attractive benefits await survey respondents! </h3>
    <br> <br>
    <h4> To facilitate your usage of this platform, check out the links below: </<h4>
    <br> <br>
      <h3>
      <a href="https://docs.google.com/document/d/1xK0bmO4I708Ml9_XBN5KzOvGIfXUPCN8UnNoH0rhJ5c/edit?usp=sharing" target="_blank"> User Guide </a>
      <br> <br>
      <a href="https://github.com/NUadS/NUadS.git" target="_blank"> GitHub Repository </a>
      </h3>
    <br>
    <h4 id="Copyright"> Created by Sabrina Yeo & Tee Kah Ming
    <br>Orbital 2020 | NUS School of Computing </h4>

  </div>

<div id="hero-slides">
  <div id="header">
    <div id="logo"></div>
  </div>

  <form method="get">
    <div class="filter-form">
    <span class="glyphicon glyphicon-filter filter" aria-hidden="true" style="color:white"> Filter: </span>
    <div>
    <label for="survey-title" class="login__label"> Survey Title</label>
    {{dashboardfilter.form.surveytitle}}
    </div>

    <div>
    <label for="survey-cat" class="login__label"> Survey Category</label>
    {{dashboardfilter.form.surveycategory}}
    </div>

    <div>
    <button class='search' type="submit">Search</button>
    </div>

  </div>
  </form>

  <div id="slides-cont">
    <div class="button" id="next"></div>
    <div class="button" id="prev"></div>

    <div id="slides">
      {% for survey in dashboardfilter.qs %}
      <div class="slide">
        <div class="number">{{survey.uploadDate}}</div>
        <div class="body">

          <div class="location"> <span class="glyphicon glyphicon-user" aria-hidden="true" style="color:white"> </span> {{survey.user}} &nbsp <span class="glyphicon glyphicon-tags" aria-hidden="true" style="color:white"> </span> {{survey.surveycategory}}</div>
          <div class="headline">{{survey.surveytitle}}</div>
          <a href="{% url 'survey:completedsurveys_update' pk=survey.pk %}" target="_self" onclick="window.open('{{survey.surveylink}}');">
            <div class="link">DO SURVEY</div>
          </a>
          <div class="details">
            {{survey.surveydescription}}
          </div>

        </div>
      </div>
      {% endfor %}
    </div>

    <div id="next-catch"></div>
    <div id="prev-catch"></div>
  </div>
  <div id="footer"><a href="https://maglatov.com/blog/all" target="_blank">
      <div id="dribbble"></div></a></div>
</div>









<script>
let hero = document.getElementById('hero-slides');
let menu = document.getElementById('blogmenu');
let slides = document.getElementById('slides');
let dribbble = document.getElementById('dribbble');
let next = [ 'next', 'next-catch' ].map(n => document.getElementById(n));
let prev = [ 'prev', 'prev-catch' ].map(n => document.getElementById(n));
let slideChildren = slides.children;
let slideCount = slides.children.length;
let currentlyDemoing = false;
let currentPage = 0;
let slidesPerPage = () => window.innerWidth > 1700 ? 4 : window.innerWidth > 1200 ? 3 : 2;
let maxPageCount = () => slideCount / slidesPerPage() - 1;

function goToPage(pageNumber = 0) {
	currentPage = Math.min(maxPageCount(), Math.max(0, pageNumber));
	console.log(currentPage);
	hero.style.setProperty('--page', currentPage);
}

function sleep(time) {
	return new Promise(res => setTimeout(res, time));
}

function hoverSlide(index) {
	index in slideChildren &&
		slideChildren[index].classList.add('hover');
}

function unhoverSlide(index) {
	index in slideChildren &&
		slideChildren[index].classList.remove('hover');
}

async function demo() {
	if(currentlyDemoing) {
		return;
	}
	currentlyDemoing = true;
	if(currentPage !== 0) {
		goToPage(0);
		await sleep(800);
	}
	let slides = slidesPerPage();
	let pageSeq_ = { 2: [ 1, 2, 1 ], 3: [ 1, 2, 1 / 3 ], 4: [ 1, 1, 0 ] };
	let pageSeq = pageSeq_[slides] || pageSeq_[4];
	let slideSeq_ = { 2: [ 2, 4, 3 ], 3: [ 3, 6, 2 ], 4: [ 3, 6, 2 ] };
	let slideSeq = slideSeq_[slides] || slideSeq_[2];
	await sleep(300);
	goToPage(pageSeq[0]);
	await sleep(500);
	hoverSlide(slideSeq[0]);
	await sleep(1200);
	goToPage(pageSeq[1]);
	dribbble.classList.add('hover');
	unhoverSlide(slideSeq[0]);
	await sleep(500);
	hoverSlide(slideSeq[1]);
	await sleep(1200);
	goToPage(pageSeq[2]);
	unhoverSlide(slideSeq[1]);
	await sleep(300);
	hoverSlide(slideSeq[2]);
	await sleep(1600);
	goToPage(0);
	unhoverSlide(slideSeq[2]);
	dribbble.classList.remove('hover');
	currentlyDemoing = false;
}

next.forEach(n => n.addEventListener('click', () => !currentlyDemoing && goToPage(currentPage + 1)));
prev.forEach(n => n.addEventListener('click', () => !currentlyDemoing && goToPage(currentPage - 1)));
menu.addEventListener('click', demo);

sleep(100).then(demo);
</script>

{%endblock%}

survey/templates/survey/redeemedrewards.html
{% extends "survey/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'survey/rewards.css' %}">
{% endblock %}

{% block navbar %}
<div class="nav_box">
<header class="navbarheader">
<div class=nav>
  <ul class=navbarlist>
    <a href="{% url 'survey:dashboard' %}" role="button">Home</a>
    <a href="{% url 'accounts:profile' %}" role="button">Profile</a>
    <a href="{% url 'survey:survey' %}" role="button" >Survey</a>
    <a href="{% url 'survey:shoprewards' %}" role="button" class="active">Rewards</a>
    <a href="{% url 'survey:report' %}" role="button">Report</a>
    <a href="{% url 'logout' %}" id="logout">Logout</a>
  </ul>
</div>
</header>
</div>
{% endblock %}



{% block body_block %}
{% load widget_tweaks %}
<div class="points">
  Total available points: 
{% for user in displayedpoints %}
  {{user.points}}
{% endfor %}
</div>
<section>
  <nav>
    <div></div>
    <ul>
      <li onclick="window.location.href='/shoprewards'">
      Shop Rewards
      </li>
      <li onclick="window.location.href='/redeemedrewards'" class="active1">
      Redeemed Rewards
    </li>
    <li onclick="window.location.href='/usedrewards'">
      Used Rewards
    </li>

    </ul>
  </nav>
</section>


<div class="reward">
<h2> Redeemed Rewards:

  {% for reward in allredeemedrewards %}
  <div class="indiv">
    <div class="uh-image">
      <img class="uh-image-inner" src="{{reward.reward_pic.url}}">
    </div>
    <div class="title">
    {{reward.rewardtitle}}
    </div>
  <div class="des">
    Survey Description:
    {{reward.rewarddescription}}
  </div>
  <div class="pts">
    Points to Redeem:
    {{reward.requiredpoints}}
  </div>
  <div class="btns">
     <a class="btn" href="{% url 'survey:used_update' pk=reward.pk %}" >Use Reward!</a>
  </div>
  </div>
  
  {% endfor %}
</h2>


</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="{% static 'survey/nav.js' %}"></script>




{% endblock %}

survey/templates/survey/survey.html
{% extends "survey/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'survey/survey.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kulim Park">
{% endblock %}

{% block navbar %}
<div class="nav_box">
<header class="navbarheader">
<div class=nav>
  <ul class=navbarlist>
    <a href="{% url 'survey:dashboard' %}" role="button">Home</a>
    <a href="{% url 'accounts:profile' %}" role="button">Profile</a>
    <a href="{% url 'survey:survey' %}" role="button" class="active">Survey</a>
    <a href="{% url 'survey:shoprewards' %}" role="button" >Rewards</a>
    <a href="{% url 'survey:report' %}" role="button">Report</a>
    <a href="{% url 'logout' %}" id="logout">Logout</a>
  </ul>
</div>
</header>
</div>
{% endblock %}



{% block body_block %}

<div id="survey">

        <div class="sign">
          <span class="flicker">SURVEY</span>
          <br></br>
          SECTION
        </div>

        <div class="btns">
          <a class="btn" href="{% url 'survey:uploadsurvey' %}" role="button">Upload Survey</a>
          <a class="btn" href="{% url 'survey:tracksurvey' %}" role="button">Created Surveys</a>
          <a class="btn" href="{% url 'survey:completedsurveys' %}" role="button"> Completed Surveys </a>
        </div>


</div>

{% endblock %}

survey/templates/survey/uploadsurvey_detail.html
{% extends "survey/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'survey/uploadsurvey_detail.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'survey/uploadsurvey.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/profile.css'%}">
{% endblock %}

{% block navbar %}
<div class="nav_box">
<header class="navbarheader">
<div class=nav>
  <ul class=navbarlist>
    <a href="{% url 'survey:dashboard' %}" role="button">Home</a>
    <a href="{% url 'accounts:profile' %}" role="button">Profile</a>
    <a href="{% url 'survey:survey' %}" role="button" class="active">Survey</a>
    <a href="{% url 'survey:shoprewards' %}" role="button" >Rewards</a>
    <a href="{% url 'survey:report' %}" role="button">Report</a>
    <a href="{% url 'logout' %}" id="logout">Logout</a>
  </ul>
</div>
</header>
</div>
{% endblock %}


{% block body_block %}
{% load widget_tweaks %}
<div class=detail-box>
<h1> {{object.surveytitle}} </h1>
<div>
    <ul class="utility-list">
      <span class="glyphicon glyphicon-user" aria-hidden="true" style="color:white"> </span>
      <li class="user">{{object.user}}</li>
      <span class="glyphicon glyphicon-time" aria-hidden="true" style="color:white"> </span>
      <li class="date">{{object.uploadDate}}</li>
      <span class="glyphicon glyphicon-tags" aria-hidden="true" style="color:white"> </span>
      <li class="tags">{{object.surveycategory}}</li>
    </ul>
</div>

  <div class=form-row>

    <label for="surveylink" class="login__label"> Survey Link </label>
    <div class="surveylinkbutton">
    {{object.surveylink}}
    </div>

  </div>

  <div class=form-row>

    <label for="surveydescription" class="login__label"> Survey Description </label>

    <div class="surveylinkbutton">
        {{object.surveydescription}}

    </div>

  </div>



  <!-- Add target audience stuff here -->
  <div class="box">
    <a href="{% url 'survey:updatesurvey' object.id %}" id="edit-button">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Edit
    </a>
</div>

<div class="box">
    <a href="{% url 'survey:deletesurvey' object.id %}" id="delete-button">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Delete
    </a>
</div>

<div class="back">
    <button onclick=history.back() class="back-button"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:white"> </span></button>
</div>

</div>

{% endblock %}