Orbital/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from accounts import views as accounts_views
from survey import views as survey_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

# urlpatterns = [
#     path('accounts/', include('accounts.urls')),
#     path('admin/', admin.site.urls)
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('survey.urls')),
    url(r'^$',accounts_views.index,name='index'),
    url(r'^special/',accounts_views.special,name='special'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^accounts/profile/',accounts_views.profile_view, name='profile'),
    url(r'^logout/$', accounts_views.user_logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import url
from . import views

app_name = 'accounts'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('login/',views.login_view,name='login'),
#     path('signup/',views.signup_view, name='signup')
# ]

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login, name='user_login'),
    url(r'^profile/$', views.profile_view, name='profile')
    
]

survey/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import url
from survey import views as survey_views
from accounts import views as accounts_views
from .views import SurveyListView, SurveyDetailView, SurveyCreateView, SurveyUpdateView, SurveyDeleteView


app_name = 'survey'

urlpatterns=[
    path('dashboard/', survey_views.dashboard_view, name='dashboard'),
    path('survey/', survey_views.survey_view, name='survey'),
    path('uploadsurvey/', SurveyCreateView.as_view(), name='uploadsurvey'),
    #path('tracksurvey/', SurveyListView.as_view() , name='tracksurvey'),
    path('tracksurvey/', survey_views.tracksurvey_view , name='tracksurvey'),
    path('tracksurvey/survey/<int:pk>/', SurveyDetailView.as_view() , name='tracksurvey-detail'),
    path('rewards/', survey_views.rewards_view, name='rewards'),
    path('tracksurvey/survey/<int:pk>/update/', SurveyUpdateView.as_view(), name='updatesurvey'),
    path('tracksurvey/survey/<int:pk>/delete/', SurveyDeleteView.as_view(), name='deletesurvey'),
    path('completedsurveys/', survey_views.completedsurveys_view , name='completedsurveys'),
    path('dashboard/<int:pk>/', survey_views.completedsurveys_update , name='completedsurveys_update'),
    path('rewards/', survey_views.rewards_view, name='rewards'),
    path('shoprewards/', survey_views.shoprewards_view, name='shoprewards'),
    path('rewards/<int:pk>', survey_views.redeem_update, name='redeem_update'),
    path('redeemedrewards/', survey_views.redeemedrewards_view , name='redeemedrewards'),
    path('redeemedrewards/<int:pk>', survey_views.used_update, name='used_update'),
    path('usedrewards/', survey_views.usedrewards_view, name='usedrewards'),
    path('report/', survey_views.report_view, name='report'),
    path('privacy/', survey_views.privacy_view, name='privacy')

]

accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User
from .models import UserProfileInfo 

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'type':"password"}))
    class Meta():
        model = User
        fields = ('username','password')
        widgets={
            'username':forms.TextInput(attrs={'type':'text'}),
        }

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('matriculationNumber','age','dob','gender','nationality', 'singaporean',
         'faculty','degree','year_in_school','currentresidentialtype',
         'portfolio_site','profile_pic','email')
         
         widgets={
            'nationality': forms.Select(attrs={'style': 'width:200px'}),
            'singaporean':forms.Select(attrs={'style':'width:200px'}),
            'faculty': forms.Select(attrs={'style':'width:220px'}),
            'currentresidentialtype':forms.Select(attrs={'style':'width:130px'}),
            'gender':forms.Select(attrs={'style':'width:140px'}),
            'year_in_school':forms.Select(attrs={'style':'width:140px'})
        }
        

class UserUpdateForm(forms.ModelForm):
    class Meta():
         model = User
         fields=['username',]
         widgets={
            'username':forms.TextInput(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'}),
        }

         
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=UserProfileInfo
        fields=('matriculationNumber','age','dob','gender','nationality','singaporean',
         'faculty','degree','year_in_school','currentresidentialtype',
         'portfolio_site','profile_pic','email')

        widgets={

            'email': forms.TextInput(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'}),
            'nationality': forms.Select(attrs={'id':'login-input-user', 'class':'login__input','style': 'width:330px'}),
            'singaporean': forms.Select(attrs={'id':'login-input-user','class':'login__input','style':'width:150px'}),
            'faculty': forms.Select(attrs={'id':'login-input-user', 'class':'login__input','style':'width:250px'}),
            'currentresidentialtype':forms.Select(attrs={'id':'login-input-user', 'class':'login__input','style':'width:130px'}),
            'gender':forms.Select(attrs={'id':'login-input-user', 'class':'login__input','style':'width:150px'}),
            'year_in_school':forms.Select(attrs={'id':'login-input-user', 'class':'login__input','style':'width:250px'}),
            'matriculationNumber':forms.TextInput(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'}),
            'age':forms.NumberInput(attrs={'id':'login-input-user', 'class':'login__input'}),
            'dob':forms.TextInput(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'}),
            'degree':forms.TextInput(attrs={'type':'text', 'id':'login-input-user', 'class':'login__input'}),
            'currentresidentialtype':forms.Select(attrs={'id':'login-input-user', 'class':'login__input','style':'width:280 px'})
             
        }

accounts/views.py
from .models import UserProfileInfo
from django.shortcuts import render,redirect
from accounts.forms import UserForm,UserProfileInfoForm,UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def index(request):
    if request.user.is_authenticated:
        return redirect('survey:dashboard')
    else:
        return render(request, 'accounts/index.html') 

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

@login_required
def profile_view(request):
    if request.method == 'POST':
        user_form=UserUpdateForm(request.POST, instance=request.user)
        profile_form=ProfileUpdateForm(request.POST,request.FILES, instance=request.user.userprofileinfo)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile = profile_form.save(commit=False)
            user = user_form.save()
            user.email=profile.email
            user.save()
            profile.save()
            messages.success(request, 'Your profile is successfully updated!')
            return redirect('profile')
        else:
            messages.error(request,user_form.errors)
            messages.error(request,profile_form.errors)
    else:
        user_form=UserUpdateForm(instance=request.user)
        profile_form=ProfileUpdateForm(instance=request.user.userprofileinfo)

    return render(request, 'accounts/profile.html', {'user_form':user_form, 'profile_form':profile_form})

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            user.email=profile.email
            user.save()
            registered = True
            return redirect('survey:privacy')

        else:
            messages.error(request,user_form.errors)
            messages.error(request,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'accounts/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect('survey:dashboard')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'accounts/login.html', {})

accounts/templates/accounts/base.html
{%load static%}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width">
    <title>Before Login Base Pages</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'survey/base.css' %}">

    {% block css %}
    {% endblock %}

</head>
  <body>
    {% if messages %}
    <ul class="messages">
      {% for msg in messages %}
      <li>
        <div class="alert alert-{{msg.level_tag}}" role="alert">
          {{msg.message}}
        </div>
      </li>
      {% endfor %}
    </ul>
    {% endif %}

      {% block body_block %}
      {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/index.html
{% extends "accounts/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/index.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kulim Park">
{% endblock %}


{% block body_block %}
<div id="index">
    
        <div class="sign">
          <span class="flicker">NU</span>advert<span class="flicker">S</span>
        </div>

        <div class="btns">
          <a class="btn" href="{% url 'accounts:user_login' %}" role="button">Login</a>
          <a class="btn" href="{% url 'accounts:register' %}" role="button">Register</a>
        </div>
        
 
</div>
    
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/accounts.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'survey/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/login.css' %}">
{% endblock %}


{% block body_block %}

  <div id="login-box" class="box">
    <h2>Login</h2>
    <form method="POST" action="{% url 'accounts:user_login' %}" id="login_form" >
      {% csrf_token %}
      <div class="user-box">
        <input type="text" name="username" required="">
        <label for="username">Username</label>
      </div>
      <div class="user-box">
        <input type="password" name="password" required="">
        <label for="password">Password</label>
      </div>
      <a href="#" onclick= "document.getElementById('login_form').submit()" id="login-submit-button">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Login
      </a>
    </form>
    <br> 
    <div class="text-muted">
    ---------------------------- OR ---------------------------
  </div>

    <div class="row">
      <div class="col-md-12">
        <a class="btn btn-outline-dark" href="{% url 'social:begin' 'google-oauth2' %}" role="button" style="width:320px; text-transform:none; background-color: brown;color:white">
          <img width="20px" style="margin-bottom:3px; margin-right:5px;" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
          Login with Google
        </a>
      </div>
    </div>

      <div class="row">
      <div class="col-md-12">
        <a class="btn btn-outline-light" href="{% url 'social:begin' 'facebook' %}" role="button" style="width:320px;text-transform:none; background-color: rgba(70, 70, 243, 0.548);color:white">
          <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Facebook sign-in" src="https://upload.wikimedia.org/wikipedia/commons/c/cd/Facebook_logo_%28square%29.png" />
          Login with Facebook
        </a>
      </div>
    </div>
    

    <div class="text-muted">
      <br>
      <br> Forgot Password? Click <a href="{% url 'password_reset' %}"> here</a>
      <br> Not a user? Register <a href="{% url 'accounts:register' %}"> here</a>
      <br> &copy NUadvertS 2020
    </div>
  </div>

  {% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/accounts.css' %}"><link rel="stylesheet" type="text/css" href="{% static 'survey/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/reset.css' %}">
{% endblock %}


{% block body_block %}

  <div id="login-box" class="box">
    <h2>Reset Password</h2>
    <form method="POST" action="" id="reset_form" >
      {% csrf_token %}
      <div class="user-box">
        {{form.email}}
        <label for="email">Email</label>
      </div>
      
    
      <a href="#" onclick= "document.getElementById('reset_form').submit()" id="login-submit-button">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Reset
      </a>
    </form>

  </div>

  {% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "accounts/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/index.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kulim Park">
{% endblock %}


{% block body_block %}
<h1 id="reset">
Your password has been set.
<br>
<br>
Click <a href="{% url 'accounts:user_login' %}" > here </a> to login.
</h1>    
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/accounts.css' %}"><link rel="stylesheet" type="text/css" href="{% static 'survey/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/reset.css' %}">
{% endblock %}


{% block body_block %}

  <div id="login-box" class="box">
    <h2>Reset Password</h2>
    <form method="POST" action="" id="reset_confirm_form" >
      {% csrf_token %}
      
      <div class="user-box">
       
        {{form.new_password1}}
        <label for="email">New Password</label>
      </div>

      <div class="user-box">
        {{form.new_password2}}
        <label for="email">New Password Confirmation</label>
      </div>

      <a href="#" onclick= "document.getElementById('reset_confirm_form').submit()" id="login-submit-button">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Reset Password
      </a>
    </form>

  </div>

  {% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "accounts/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/index.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kulim Park">
{% endblock %}


{% block body_block %}
<h1 id='reset'>
An email has been sent with instructions to reset your password.
</h1>    
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "survey/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/profile.css' %}">
{% endblock %}

{% block navbar %}
<div class="nav_box">
<header class="navbarheader">
<div class=nav>
  <ul class=navbarlist>
    <a href="{% url 'survey:dashboard' %}" role="button">Home</a>
    <a href="{% url 'accounts:profile' %}" role="button" class="active">Profile</a>
    <a href="{% url 'survey:survey' %}" role="button">Survey</a>
    <a href="{% url 'survey:shoprewards' %}" role="button">Rewards</a>
    <a href="{% url 'survey:report' %}" role="button">Report</a>
    <a href="{% url 'logout' %}" id="logout">Logout</a>
  </ul>
</div>
</header>
</div>
{% endblock %}


{% block body_block %}
<div class="profile_box">
<div class="uh-image">
    <img class="uh-image-inner" src="{{user.userprofileinfo.profile_pic.url}}">

</div>
<div class="profile_header">
    <h2 id="profile_header"> {{ user.username }}</h2>
</div>

<div class="container">
    <form enctype="multipart/form-data" method="POST" action="{% url 'accounts:profile' %}" id="profileupdate_form" class="form-login">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                <label for="username" class="login__label"> Username</label>
                {{user_form.username}}
            </div>

            <div class="form-group col-md-6 mb-0">
                <label for="email" class="login__label"> Email </label>
                {{ profile_form.email}}
            </div>

        </div>

        <div class="form-row">
            <div class="form-group col-md-12 mb-0">
                <label for="dob"  class="login__label"> Date of Birth </label>
                {{ profile_form.dob}}
                <div class="help_text">
                {{profile_form.dob.help_text}}
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                <label for="nationality" class="login__label"> Citizen Of </label>
                {{ profile_form.nationality}}
            </div>

            <div class="form-group col-md-2 mb-0">
                <label for="singaporean" class="login__label"> Singaporean? </label>
                {{profile_form.singaporean}}
            </div>

            <div class="form-group col-md-2 mb-0">
                <label for="age" class="login__label"> Age </label>
                {{ profile_form.age}}
            </div>

            <div class="form-group col-md-2 mb-0">
                <label for="gender" class="login__label"> Gender </label>
                {{ profile_form.gender}}
            </div>

            <div class="form-group col-md-2 mb-0">
                <label for="currentresidentialtype" class="login__label"> Residential Type </label>
                {{ profile_form.currentresidentialtype}}
            </div>

        </div>



        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                <label for="matriculationNumber" class="login__label"> Matric Number </label>
                {{ profile_form.matriculationNumber}}
                <div class="help_text">
                {{profile_form.matriculationNumber.help_text}}
                </div>
            </div>

            <div class="form-group col-md-3 mb-0">
                <label for="year_in_school" class="login__label"> Year in School </label>
                {{ profile_form.year_in_school}}
            </div>

            <div class="form-group col-md-3 mb-0">
                <label for="faculty" class="login__label"> Faculty </label>
                {{ profile_form.faculty}}
            </div>

            <div class="form-group col-md-12 mb-0">
                <label for="degree" class="login__label"> Degree </label>
                {{ profile_form.degree }}
            </div>

        </div>

        <div class="form-row">
            <div class="form-group col-md-12 mb-0">
                <label for="profile_pic" class="login__label" id="pic"> Profile Picture</label>
                <div class="pic_text">    
                    
                        {{ profile_form.profile_pic}}

                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12 mb-0">
                <div class="box">
                    <a href="#" onclick= "document.getElementById('profileupdate_form').submit()" id="update-button">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        Update
                    </a>
                </div>
            </div>
        </div>


	</form>

</div>

{% endblock %}

accounts/templates/accounts/registration.html
{% extends "accounts/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/accounts.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'survey/index.css' %}">
{% endblock %}



{% block body_block %} 
<div id="registration-box" class="box">
      {% if registered %}
        <h1>You have successfully created your account. Thank you for registering!</h1>
      {% else %}
        <h2> Create your account</h2>

        <!-- Form -->
        <form enctype="multipart/form-data" method="POST" action="{% url 'accounts:register' %}" id="registration_form">
          {% csrf_token %}
        <!-- Username & PW in same row -->

          <div class="user-box">
                {{user_form.username}}
                <label for="username"> Username * </label>
          </div>
          <div class="user-box">
                {{ user_form.password}}
                <label for="password"> Password * </label>
          </div>

          <!-- Email to be in a single row -->
          <div class="user-box">
                {{ profile_form.email}}
                <label for="email"> Email * </label>
          </div>

          <!-- nationality, age, dob, gender, residential type to be in a single row -->
          <div class="form-row user-box">
            <div class="form-group col-md-3 mb-0">
            <div class="registration-input-dropdown">
              {{ profile_form.nationality}}
              <label for="nationality"> Citizen Of </label>
              </div>
            </div>
            <div class="form-group col-md-3 mb-0">
              <div class="registration-input-dropdown">
                {{ profile_form.singaporean}}
                <label for="singaporean"> Singaporean? * </label>
                </div>
            </div>
            <div class="form-group col-md-2 mb-0">
              <div class="registration-input">
              {{ profile_form.age}}
              <label for="age"> Age * </label>
              </div>
            </div>
            <div class="form-group col-md-4 mb-0">
              <div class="registration-input">
              {{ profile_form.dob}}
              <label for="dob"> Date of Birth * </label>
              <div class="help-text">
              {{profile_form.dob.help_text}}
            </div>
            </div>
            </div>
            <div class="form-group col-md-2 mb-0">
              <div class="registration-input-dropdown">
              {{ profile_form.gender}}
              <label for="gender"> Gender * </label>
            </div>
            </div>
            <div class="form-group col-md-2 mb-0">
              <div class="registration-input-dropdown">
              {{ profile_form.currentresidentialtype}}
              <label for="currentresidentialtype"> Residential Type * </label>
            </div>
            </div>
          </div>


          <!-- matric in one row  -->
            <div class="form-row user-box">
            <div class="form-group col-md-6 mb-0">
              <div class="registration-input">
              {{ profile_form.matriculationNumber}}
              <label for="matriculationNumber"> Matric Number * </label>
              <div class="help-text">
              {{profile_form.matriculationNumber.help_text}}
              </div>
            </div>
            </div>
          </div>

          <!-- year, faculty, degree in one row  -->
          <div class="form-row user-box">
            <div class="form-group col-md-2 mb-0">
              <div class="registration-input-dropdown">
              {{ profile_form.year_in_school}}
              <label for="year_in_school"> Year in School * </label>
            </div>
            </div>

            <div class="form-group col-md-3 mb-0">
              <div class="registration-input-dropdown">
              {{ profile_form.faculty}}
              <label for="faculty"> Faculty * </label>
            </div>
          </div>

            <div class="form-group col-md-9 mb-0">
              <div class="registration-input">
              {{ profile_form.degree}}
              <label for="degree"> Degree * </label>
            </div>
            </div>


        </div>


          <!-- profile pic in one row -->
          <div class="user-box" id="pic2">
            <div class="form-group col-md-12 mb-0">
              <div>
                <label for="profile_pic" id="pic"> Profile Picture</label>
                {{ profile_form.profile_pic}}
            </div>
            </div>
          </div>

          <!-- Submit Button-->
          <a href="#" onclick= "document.getElementById('registration_form').submit()" id="registration-submit-button">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
              Submit
          </a>
        </form>

        <div class="text-muted" id="reglog" >
         Already a user? Login <a href="{% url 'accounts:user_login' %}">here</a>
         <br> &copy NUadvertS 2020
        </div>

      {% endif %}
  </div>
{% endblock %}